package com.BikkadIT.AutoWiringModes.dao;

import org.springframework.stereotype.Repository;

@Repository("report1")
public class MySQLReport implements ReportDao {

	@Override
	public void generateReport() {
		System.out.println("Report Generated By MySQL Database.");
		
	}

}
