package com.BikkadIT.AutoWiringModes.dao;

import org.springframework.stereotype.Repository;

@Repository("report2")
public class OracleReport implements ReportDao {

	@Override
	public void generateReport() {
		System.out.println("Report Generated By Oracle Database.");
		
	}

}
